
def Replace_emoji(sent):
    '''
    
    Chaning written emojis to meaningful text for NLP applications. 
    
    Parameters
    
    ----------
    sent : str (sentence) 
        The sent is a text containg emojis, i.e. 
        Input: 'The weather is really bad :( '

    Returns
    -------
    sent : str (sentence)
    Output: 'The weather is really bad :( '
        

    '''    
    emojis = {'(⁄ ⁄•⁄ω⁄•⁄ ⁄)': 'embarrassed',
         '((d[-_-]b))': 'headphones',
         '(^.^)y-.o○': 'smoking',
         '(-.-)y-°°°': 'smoking',
         '(°-°)(°.°)': 'confused',
         "@}‑;‑'‑‑‑": 'rose',
         '>_>^ ^<_<': 'high five',
         '(;_;)/~~~': 'waving',
         '(^.^)/~~~': 'waving',
         '(-_-)/~~~': 'waving',
         '($··)/~~~': 'waving',
         '(@^^)/~~~': 'waving',
         '(T_T)/~~~': 'waving',
         '(ToT)/~~~': 'waving',
         '\\ (^o^) /': 'excited',
         '(::[]::)': 'bandage',
         '(-_-)zzz': 'sleeping',
         '<m(__)m>': 'a sign of respect',
         '(^^)/~~~': 'waving',
         ':‑###..': 'being sick',
         '@>‑‑>‑‑': 'rose',
         '(^_-)-*': 'wink',
         '((+_+))': 'confused',
         '_(._.)_': 'a sign of respect',
         '_(_^_)_': 'a sign of respect',
         '<(_ _)>': 'a sign of respect',
         'm(_ _)m': 'a sign of respect',
         '(*^_^*)': 'normal laugh',
         '(*^.^*)': 'normal laugh',
         '(#^.^#)': 'normal laugh',
         '(^_^)/~': 'waving',
         '\\(~o~)/': 'excited',
         '\\(-o-)/': 'excited',
         '(*^0^*)': 'excited',
         '\\(^o^)/': 'hopeless',
         '(^0_0^)': 'eyeglasses',
         '(^)o(^)': 'happy',
         ':###..': 'being sick',
         '@}->--': 'rose',
         '(>_<)>': 'troubled',
         '(^_^;)': 'embarrassed',
         '(-_-;)': 'embarrassed',
         '(~_~;)': 'embarrassed',
         '(・.・;)': 'embarrassed',
         '(・_・;)': 'embarrassed',
         '(°_°>)': 'confused',
         '(^_^)/': 'joyful',
         '(^O^)/': 'joyful',
         '(^o^)/': 'joyful',
         'm(__)m': 'a sign of respect',
         '(^_^.)': 'normal laugh',
         '(^__^)': 'normal laugh',
         '(@_@;)': 'amazed',
         '(*^^)v': 'laughing',
         '(^_^)v': 'laughing',
         '(’-’*)': 'laughing',
         '(￣□￣;)': 'surprised',
         ':O o_O': 'surprised',
         '(>_<)': 'troubled',
         '(>w<)': 'troubled',
         "(';')": 'baby',
         '(・・;)': 'embarrassed',
         '(^^;)': 'embarrassed',
         '(^_-)': 'wink',
         '(+o+)': 'confused',
         '(°_°)': 'confused',
         '(°o°)': 'joyful',
         '(^^)/': 'joyful',
         "('_')": 'sad',
         '(/_;)': 'sad',
         '(T_T)': 'sad',
         '(;_;)': 'sad',
         '(;_:)': 'sad',
         '(;O;)': 'sad',
         '(:_;)': 'sad',
         '(ToT)': 'sad',
         '(-.-)': 'shame',
         '(-_-)': 'shame',
         '(=_=)': 'tired',
         '(._.)': 'looking down in sadness',
         '(?_?)': 'confusion',
         '>^_^<': 'normal laugh',
         '<^!^>': 'normal laugh',
         '(^<^)': 'normal laugh',
         '(^.^)': 'normal laugh',
         '(^·^)': 'normal laugh',
         '(^_^)': 'normal laugh',
         '(^J^)': 'normal laugh',
         '(*_*)': 'amazed',
         '(*_*;': 'amazed',
         '(+_+)': 'amazed',
         '(@_@)': 'amazed',
         '(^^)v': 'laughing',
         '(^v^)': 'laughing',
         '(-"-)': 'worried',
         '(ーー;)': 'worried',
         '(^O^)': 'happy',
         '(^o^)': 'happy',
         '(￣ー￣)': 'grinning',
         '(o.o)': 'surprised',
         ':-))': 'very happy',
         ':-||': 'sad',
         ":'‑(": 'crying',
         ":'‑)": 'tears of happiness',
         "D‑':": 'horror',
         '://)': 'embarrassed',
         '://3': 'embarrassed',
         'O:‑)': 'angel',
         '0:‑3': 'angel',
         '0:‑)': 'angel',
         '0;^)': 'angel',
         '>:‑)': 'evil',
         '}:‑)': 'evil',
         '3:‑)': 'evil',
         '>;‑)': 'evil',
         '|;‑)': 'cool',
         '<:‑|': 'dumb',
         ',:-|': 'disapproval',
         '@};-': 'rose',
         '*\x00/*': 'cheerleader',
         '._.;': 'sadness',
         'o/\\o': 'high five',
         '^_^;': 'embarrassed',
         '(°°)': 'confused',
         '(__)': 'a sign of respect',
         '(;_;': 'sad',
         '(..)': 'looking down in sadness',
         '(・・?': 'confusion',
         '(^^)': 'normal laugh',
         ':‑)': 'smile',
         ':-]': 'smile',
         ':->': 'smile',
         '8-)': 'smile',
         ':-}': 'smile',
         ':o)': 'smile',
         ':c)': 'smile',
         ':^)': 'smile',
         ':‑D': 'laughing',
         '8‑D': 'laughing',
         'B^D': 'laughing',
         'x‑D': 'laughing',
         'X‑D': 'laughing',
         ':‑(': 'sad',
         ':‑c': 'sad',
         ':‑<': 'sad',
         ':‑[': 'sad',
         ":'(": 'crying',
         ':=(': 'crying',
         ":')": 'tears of happiness',
         ':"D': 'tears of happiness',
         '>:(': 'angry',
         '>:[': 'angry',
         'D:<': 'horror',
         ':‑O': 'surprise',
         ':‑o': 'surprise',
         ':-0': 'surprise',
         '8‑0': 'surprise',
         '>:O': 'surprise',
         ':-3': 'cat face',
         '>:3': 'evil cat',
         ':-*': 'kiss',
         ';‑)': 'wink',
         '*-)': 'wink',
         ';‑]': 'wink',
         ';^)': 'wink',
         ':‑,': 'wink',
         ':‑P': 'playful',
         'X‑P': 'playful',
         'x‑p': 'playful',
         ':‑p': 'playful',
         ':‑Þ': 'playful',
         ':‑þ': 'playful',
         ':‑b': 'playful',
         '>:P': 'playful',
         ':-/': 'skeptical',
         ':‑.': 'skeptical',
         '>:\\': 'skeptical',
         '>:/': 'skeptical',
         ':‑|': 'indecision',
         ':‑X': 'sealed lips',
         ':‑#': 'sealed lips',
         ':‑&': 'sealed lips',
         'O:)': 'angel',
         '0:3': 'angel',
         '0:)': 'angel',
         '>:)': 'evil',
         '}:)': 'evil',
         '3:)': 'evil',
         '>;)': 'evil',
         '|‑O': 'cool',
         'B-)': 'cool',
         ':‑J': 'tongue-in-cheek',
         '#‑)': 'partied all night',
         '%‑)': 'confused',
         ':-l': 'disapproval',
         '8-X': 'skull and crossbones',
         '8=X': 'skull and crossbones',
         'x-3': 'skull and crossbones',
         'x=3': 'skull and crossbones',
         '</3': 'broken heart',
         '\\o/': 'yay',
         'v.v': 'sadness',
         '._.': 'sadness',
         'X_X': 'dead person',
         'x_x': 'dead person',
         '+_+': 'dead person',
         'X_x': 'dead person',
         'x_X': 'dead person',
         '<_<': 'sideways look',
         '>_>': 'sideways look',
         '<.<': 'sideways look',
         '>.>': 'sideways look',
         'O_O': 'surprise',
         'o_o': 'surprise',
         'O-O': 'surprise',
         'o‑o': 'surprise',
         'O_o': 'surprise',
         'o_O': 'surprise',
         '>.<': 'undecided',
         '>_<': 'undecided',
         '^^;': 'embarrassed',
         'zzz': 'sleeping',
         ';_;': 'sad',
         ';-;': 'sad',
         ';n;': 'sad',
         'Q.Q': 'sad',
         'T.T': 'sad',
         'TnT': 'sad',
         'Q_Q': 'sad',
         '^m^': 'giggling',
         '^/^': 'normal laugh',
         '^_^': 'normal laugh',
         '^o^': 'happy',
         '°o°': 'surprised',
         '°O°': 'surprised',
         'o_0': 'surprised',
         'o.O': 'surprised',
         'uwu': 'joy',
         'UwU': 'joy',
         ':)': 'smile',
         ':]': 'smile',
         ':>': 'smile',
         '8)': 'smile',
         ':}': 'smile',
         '=]': 'smile',
         '=)': 'smile',
         ':D': 'laughing',
         '8D': 'laughing',
         '=D': 'laughing',
         'c:': 'laughing',
         'C:': 'laughing',
         'xD': 'laughing',
         'XD': 'laughing',
         ':(': 'sad',
         ':c': 'sad',
         ':<': 'sad',
         ':[': 'sad',
         ':{': 'sad',
         ':@': 'sad',
         ';(': 'sad',
         'D:': 'horror',
         'D8': 'horror',
         'D;': 'horror',
         'D=': 'horror',
         'DX': 'horror',
         ':O': 'surprise',
         ':o': 'surprise',
         ':0': 'surprise',
         '=O': 'surprise',
         '=o': 'surprise',
         '=0': 'surprise',
         ':3': 'cat face',
         '=3': 'cat face',
         'x3': 'cat face',
         'X3': 'cat face',
         ':*': 'kiss',
         ':×': 'kiss',
         ';)': 'wink',
         '*)': 'wink',
         ';]': 'wink',
         ';>': 'wink',
         ';D': 'wink',
         ';3': 'wink',
         ':P': 'playful',
         'XP': 'playful',
         'xp': 'playful',
         ':p': 'playful',
         ':Þ': 'playful',
         ':þ': 'playful',
         ':b': 'playful',
         'd:': 'playful',
         '=p': 'playful',
         ':/': 'skeptical',
         ':\\': 'skeptical',
         '=/': 'skeptical',
         '=\\': 'skeptical',
         ':L': 'skeptical',
         '=L': 'skeptical',
         ':S': 'skeptical',
         ':s': 'skeptical',
         ':|': 'indecision',
         ':$': 'embarrassed',
         ':X': 'sealed lips',
         ':#': 'sealed lips',
         ':&': 'sealed lips',
         '%)': 'confused',
         ':E': 'nervous',
         '<\x03': 'broken heart',
         '<3': 'heart',
         'o7': 'salute',
         'QQ': 'crying',
         'qq': 'crying',
         'Qq': 'crying',
         '^5': 'high five',
         ';;': 'sad',
         'oO': 'surprised'}
    
    for emoji in emojis.keys():
            sent = sent.replace(emoji, "EMOJI " + emojis[emoji])
            
    return sent
